### ISSUE TITLE
Support International Addresses

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#106]
International registrants cannot enter their full address. We only support us addresses. How should we support international addresses?

**Comment by ColinW520** [comment]
We do _zero_ country validation. This is intentional. We do, however, just need to add it to the dropdown. This is very easy.

Right now I'm adding these countries. Please let me know if you would like to add other ones. I am also adding an option that looks like "-------", which, **ANYONE** can use since, again, we do zero validation around this.

```
["Australia", "Australia"],
      ["Canada", "Canada"],
      ["France", "France"],
      ["Germany", "Germany"],
      ["Mexico", "Mexico"],
      ["New Zealand", "New Zealand"],
      ["South Africa", "South Africa"],
      ["United Kingdom", "United Kingdom"],
```

**Comment by ColinW520** [comment]
Note: removing zip code validation from the front-end. Since this isn't used _anywhere_, it really shouldn't be validated. Its just for completeness, should you ever want to send someone mail.

**Comment by runbeyond** [comment]
Thanks, Colin!
