### ISSUE TITLE
COVID-19 Operating Procedures

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#162]
Maybe a dedicated landgin page? Maybe something else? Here is the problem statement:

We need to provide an easy to find, prominent statement of our “COVID-19 response” which is essentially a detailed outline of operating procedures that are unique to the context of living in a pandemic.

**Comment by willblake01** [comment]
@ColinW520 @runbeyond Would you say this is the highest priority of things I can probably contribute to? I want to work on something this weekend while Colin has a chance to review the testing I added to that PR.

**Comment by ColinW520** [comment]
@willblake01 let's get a landing page setup for this, and link to it via the header, with a special background color.

@runbeyond -- how's that sound?

**Comment by willblake01** [comment]
@runbeyond @ColinW520 I'm on it! Does it make more sense to add the link to the navbar or create a section just above the header? Putting it in a dedicated section seems like it would draw more attention to it but I'm unsure if that's the goal or not.

**Comment by runbeyond** [comment]
That sounds great, Colin!

Thank you

**Comment by willblake01** [comment]
@runbeyond Thoughts on the background color? I just set it to blue for now since it represents stability, trust, calming, etc. Also, I saw some race specific COVID updates but do you have the copy ready to drop into this page?

**Comment by runbeyond** [comment]
@willblake01 I like the background color. I am running through a final edit of the copy with Mallory and will post here ASAP. Thanks!

**Comment by runbeyond** [comment]
@willblake01 you can access copy here: https://docs.google.com/document/d/1cw1Lax-4LVGwxxmoikKD8MVPUjIKZ7YsT0RVhS6rldc/edit

We just need the content from pages 3-5

What do you think about a photo or something on the page to help with aesthetics?

**Comment by willblake01** [comment]
@runbeyond Thanks! I've added the copy to the covid page against the blue background. Can you pull down the branch and fire it up locally and let me know what you think? I borrowed the container layout from the /about page so see how you like the width, we can definitely make it wider or change anything else. We can add a photo if you'd like, we could set it behind the opaque blue or ditch the blue altogether. Let me know yo!

**Comment by willblake01** [comment]
@runbeyond @ColinW520 Here's the page with the copy added. I added the gem that allows us to use Markdown for page content and I have it injecting to the template from a Markdown file. Let's talk background!
![image](https://user-images.githubusercontent.com/16193879/94964860-0c358c80-04c0-11eb-9b1a-d90891ddc204.png)

**Comment by runbeyond** [comment]
Hey Will,

This looks good so far. One thing off the top, the font should match the
website font instead of the font from the document I sent.

What kind of background options are we talking?

**Comment by willblake01** [comment]
Case #1 for a style guide!
We could do something cool with a picture or logo but I feel like a real UX designer or accessibility expert would say to keep this page really simple and easy to read. In the end it's your site and I think it depends which path you want to follow, following strict design principles regarding accessibility etc. or just doing wild, crazy, and fun shit because it's your site and you want to.

**Comment by runbeyond** [comment]
@willblake01  In the intro paragraph, please add the following sentence as the opening sentence. "Please know that we value the safety of our community and are continuously working to balance your safety with our shared desired to foster community and competition within the trail running and racing community."

**Comment by willblake01** [comment]
@runbeyond I did a bunch of research on accessibility for this issue and the style guide idea. All the UX and design professionals were recommending the below style for linking to a covid page, enough to make it clear I should use this instead of the navbar button I currently have.

![image](https://user-images.githubusercontent.com/16193879/96032726-b8626600-0e24-11eb-8480-b0740c0c9b41.png)

Also, they were saying it's ok to use images in a covid page as long as they support the message. Like the one below for example. I found that it's ok to use whatever color or image background and font as long as the contrast is 4.5:1 or greater. If we find a relevant image to use we can always add a gray mask over it and adjust the opaqueness of it until the contrast is within ratio.

![image](https://user-images.githubusercontent.com/16193879/96033021-227b0b00-0e25-11eb-9198-8f11b31bd13b.png)

**Comment by runbeyond** [comment]
Okay. Can you rapidly prototype a solution? I’d like to get this across the
goal line ASAP. We get questions daily on this issue.

**Comment by willblake01** [comment]
@runbeyond I'll show you how to pull down a branch and fire it up locally again next time we meet but until then here's a couple screenshots of what I have right now. Ideally I'd like to use a more covid relevant picture but I borrowed the one from the /about page in the meantime.

![image](https://user-images.githubusercontent.com/16193879/96069071-0e55fe80-0e63-11eb-86d1-7bed1f9ad742.png)

![image](https://user-images.githubusercontent.com/16193879/96069103-1ca41a80-0e63-11eb-91a1-fbf7555520e1.png)

**Comment by runbeyond** [comment]
@willblake01 Here are some image options to try for this page background. Not sure if any will work so use your best judgment
![Spectrum Trail Race - Ft Davis -  023](https://user-images.githubusercontent.com/44638093/96149413-e7351680-0ece-11eb-9788-aa1f15a6bef5.jpg)
![Spectrum Trail Race - Ft Davis -  028](https://user-images.githubusercontent.com/44638093/96149420-eac89d80-0ece-11eb-886f-f9030bdae1d5.jpg)
![Spectrum Trail Race - Ft Davis -  042](https://user-images.githubusercontent.com/44638093/96149422-ebf9ca80-0ece-11eb-88f2-1f1851413978.jpg)
![Spectrum Trail Race - Ft Davis -  110](https://user-images.githubusercontent.com/44638093/96149425-ec926100-0ece-11eb-9ddb-454c1e37a64c.jpg)

P.S. I reduced the file size on all of these to under 1MB



!

**Comment by runbeyond** [comment]
Great job, @willblake01!
