### ISSUE TITLE
Cannot access registration details (500 error)

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#185]
When trying to access registration details for some current and past In-Progress registration records, admin users receive a 500 error.

Steps to recreate:
1) Log in to Admin console
2) Attempt to access details for registration records such as 2281 or 2621

Special Note, this behavior is not consistent. For example, it is possible to access the details for registration record #2622. This indicates a deeper issue for which @willblake01 has uncovered some relevant insights.

**Comment by willblake01** [comment]
@ColinW520 @runbeyond I found that it’s throwing the error because we’re calling .titleize on the division which is nil for all in-progress registrations that haven’t made it that far, as well as completed registrations that are affected by that bigger bug. I also need to add some logic since “race day age” is rendering as 0 since it’s calculating on a nil value.

**Comment by willblake01** [comment]
Once merged PR #186 should allow admins to view and edit those registrations.

**Comment by runbeyond** [comment]
Great job, @willblake01!
