### ISSUE TITLE
Team Registration

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#44]
I think you have an mvp idea in mind for this feature. Let's discuss that. For now, this only needs an MVP level of function.

**As a:** Spectrum racer selected as a team captain

**I want:** to register my team

**So that:** I can register for race team spot and send out invitations to my teammates to register for their team slots

*Acceptance Criteria:*

1) When registering for a team event (e.g. The Circus 12-hour relay), I can register as a team captain
2) When registering as a team captain, I can create a team
3) Once I have created a team and completed my registration process as the team captain, I can invite my remaining teammates to register as part of my team
4) I can always return to my registration record to invite new team members or send reminders to previously invited team embers
5) Each team member has to pay their share of the registration fees due for each member of the team

**Comment by ColinW520** [comment]
@runbeyond as scoped, this is a significant lift. Done as scoped, I would give this an estimate of 8 hours.

May I suggest a lighter scope for MVP?

As a: Spectrum site visitor

While I am: registering for a race

I want: to designate my team name

So that: I can compete in this race on a team with friends

Acceptance Criteria:
 - I can enter a team name on the first step of the registration process for events that support team races.

**Comment by ColinW520** [comment]
@runbeyond -- can we just close this one? Once we see how users interact with the functionality for #53, we can iterate on it, particularly in the direction of team invites and payments

**Comment by runbeyond** [comment]
Yes. You are right.
